site_name: GPT4All
repo_url: https://github.com/nomic-ai/gpt4all
repo_name: nomic-ai/gpt4all
site_url: https://docs.gpt4all.io
edit_uri: edit/main/docs/
site_description: Documentation for running GPT4All anywhere.
copyright: Copyright &copy; 2023 Nomic, Inc
use_directory_urls: false

nav:
    - 'Home': 'index.md'
    - 'Desktop': 
      - 'desktop/desktop_home.md'
      - 'Install' : 'desktop/desktop_install.md'
      - 'Explore' : 'desktop/desktop_tour.md'
      - 'RAG' : 'desktop/desktop_localdocs.md'
    - 'Python': 
      - 'python/python_home.md'
      - 'RAG': 'python/python_rag.md'
      - 'Monitoring': 'python/python_monitoring.md'
      - 'API Reference': 'python/python_ref.md'
    - 'Help':
      - 'FAQ': 'help/help_faq.md'
      - 'Troubleshooting': 'help/help_troubleshooting.md'
    - 'Old':
      - 'old/index.md'
      - 'GPT4All Chat Client': 'old/gpt4all_chat.md'
      - 'Bindings':
        - 'GPT4All in Python':
          - 'Generation': 'old/gpt4all_python.md'
          - 'Embedding': 'old/gpt4all_python_embedding.md'
          - 'Monitoring with OpenLIT': 'old/gpt4all_monitoring.md'
        - 'GPT4All in NodeJs': 'old/gpt4all_nodejs.md'
        - 'old/gpt4all_cli.md'
      - 'Wiki':
        - 'old/gpt4all_faq.md'


theme:
  name: material
  palette:
    primary: white
  logo: assets/nomic.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
#    - navigation.tabs
#    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons
  - tables
  - admonition
  - codehilite:
      css_class: highlight

extra_css:
    - css/custom.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: True
            heading_level: 4
            show_root_full_path: false
            docstring_section_style: list
  #- material/social:
  #    cards_font: Roboto

  #- mkdocs-jupyter:
  #    ignore_h1_titles: True
  #    show_input: True
